#!/usr/bin/env python3
"""
Generate config/members.yaml from MemberSS.xlsx

Reads the member master spreadsheet exported from Google Sheets (MemberSS),
filters out members on leave, and writes a YAML file embedded in the project.
This YAML is the runtime data source for the 未記入者 feature.

Usage:
    python tools/generate_member_yaml.py

Run this tool whenever MemberSS.xlsx is updated (typically with each org change).
Then commit the updated config/members.yaml.
"""

import sys
import yaml
import pandas as pd
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
XLSX_FILE = PROJECT_ROOT / 'Member.xlsx'
YAML_FILE = PROJECT_ROOT / 'config' / 'members.yaml'

OUTPUT_COLUMNS = ['mail_address', 'member_name', 'division', 'department', 'section']


def main():
    if not XLSX_FILE.exists():
        print(f"Error: {XLSX_FILE} not found")
        sys.exit(1)

    df = pd.read_excel(XLSX_FILE, engine='openpyxl')

    # Verify required columns exist
    missing = [c for c in OUTPUT_COLUMNS + ['leave'] if c not in df.columns]
    if missing:
        print(f"Error: missing columns in MemberSS.xlsx: {missing}")
        sys.exit(1)

    # Filter out members on leave (leave == 'Y'); NaN = active
    active = df[df['leave'].fillna('').ne('Y')].copy()
    left_count = len(df) - len(active)

    result = active[OUTPUT_COLUMNS].fillna('').copy()
    members = result.to_dict(orient='records')

    # Write YAML
    YAML_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(YAML_FILE, 'w', encoding='utf-8') as f:
        f.write("# Member list for WE-Dashboard\n")
        f.write("# Auto-generated by tools/generate_member_yaml.py\n")
        f.write("# Do not edit this file directly.\n")
        f.write("# Source: MemberSS.xlsx (exported from Google Sheets)\n\n")
        yaml.dump({'members': members}, f, allow_unicode=True,
                  default_flow_style=False, sort_keys=False)

    print(f"Generated {YAML_FILE}")
    print(f"  Active members : {len(members)}")
    print(f"  On leave       : {left_count}")
    print()

    # Summary by division
    by_div = result.groupby('division').size().reset_index(name='count')
    for _, row in by_div.iterrows():
        print(f"  {row['division']}: {row['count']}")


if __name__ == '__main__':
    main()
